apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
#  completions: 5
#  parallelism: 2
#  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
        - name: centos-container
          image: centos
          command: ["bash"]
          args:
            - "-c"
            - "echo 'Hello World' ; sleep 50; echo 'Bye"
      restartPolicy: Never
#      restartPolicy: onFailure
#  backoffLimit: 3