apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-resource
  labels:
    app: nginx-pod-resource
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          cpu: 200m
          memory: 250Mi
        limits:
          cpu: 1
          memory: 500Mi
      ports:
        - containerPort: 8080