apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
        - name: fluentd-elasticsearch
          image: quay.io/fluent/fluentd-kubernetes-daemonset
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-logging"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "true"
            - name: FLUENT_ELASTICSEARCH_SSL_VERSION
              value: "TLSv1_2"
            - name: testenv
              value: value
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi